# Generated by Django 5.0.6 on 2024-07-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_newsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
