# Generated by Django 5.0.6 on 2024-07-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_newsmodel_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='news-cover-image/'),
        ),
    ]
