# Generated by Django 5.0.6 on 2024-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_newsmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
